"""
era5_fetcher.py — Mediterranean Quantitative Finance Society (MQFS)
====================================================================
Downloads real ERA5 reanalysis data for Sicily from the Copernicus
Climate Data Store (CDS), or regenerates the calibrated reference
synthetic dataset that ships with the repository.

DATA SOURCE — ERA5
------------------
ERA5 is produced by the European Centre for Medium-Range Weather
Forecasts (ECMWF) and distributed by the Copernicus Climate Change
Service (C3S). It is a free, peer-reviewed, globally recognised
reanalysis product covering 1940 to present.

Citation:
  Hersbach, H. et al. (2020). The ERA5 global reanalysis.
  Q. J. R. Meteorol. Soc., 146(730), 1999–2049.
  https://doi.org/10.1002/qj.3803

Variables downloaded:
  - 2m_temperature       (°C, daily mean via 12:00 UTC snapshot)
  - total_precipitation  (mm/day, 24h accumulation)

Domain  : Sicily bounding box — lat [36.5, 38.5], lon [12.5, 15.5]
Period  : 1990-01-01 → 2023-12-31  (12,418 daily records)
Grid    : 0.25° × 0.25° → spatially averaged over the domain

REFERENCE SYNTHETIC DATASET
----------------------------
data/sicily_reference_synthetic.csv — 12,418 rows, generated by this
script, calibrated on published SIAS Palermo-Boccadifalco climate
normals (ISPRA/SIAS — Atlante Climatico della Sicilia, 2021).
⚠  NOT real measurements — a high-fidelity physically-motivated simulation.

Calibration parameters:
  Temperature : mean 18.4°C, seasonal amplitude ±9.5°C, peak day 196
                AR(1) φ=0.74, Student-t ν=6 innovations
  Rainfall    : mean 2.16 mm/day (≈790 mm/yr), Mediterranean dry-summer,
                AR(1) φ=0.46, Student-t ν=4 innovations

SETUP FOR REAL ERA5 (one-time, free)
-------------------------------------
1. Register at https://cds.climate.copernicus.eu
2. Accept ERA5 licence:
   https://cds.climate.copernicus.eu/cdsapp#!/terms/licence-to-use-copernicus-products
3. Create ~/.cdsapirc:
       url: https://cds.climate.copernicus.eu/api/v2
       key: <YOUR-UID>:<YOUR-API-KEY>
4. pip install cdsapi xarray netCDF4
5. python src/python/era5_fetcher.py --real

Author : MQFS Research Division
License: MIT
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from scipy.stats import t as student_t

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")

# ERA5 request parameters
ERA5_DATASET  = "reanalysis-era5-single-levels"
ERA5_AREA     = [38.5, 12.5, 36.5, 15.5]          # [N, W, S, E] Sicily bbox
ERA5_YEARS    = list(range(1990, 2024))             # 34 years → 12,418 records
ERA5_MONTHS   = [f"{m:02d}" for m in range(1, 13)]
ERA5_DAYS     = [f"{d:02d}" for d in range(1, 32)]
ERA5_TIME     = "12:00"
ERA5_VARS     = ["2m_temperature", "total_precipitation"]
ERA5_RAW_PATH = Path("data/era5_raw.nc")
ERA5_OUT_PATH = Path("data/weather_data.csv")

# Reference synthetic parameters
REF_PARAMS = dict(
    start      = "1990-01-01",
    end        = "2023-12-31",
    temp_mean  = 18.4,   # annual mean °C  — SIAS Palermo-Boccadifalco
    temp_amp   = 9.5,    # seasonal half-amplitude
    temp_peak  = 196,    # hottest day ≈ July 15
    temp_ar1   = 0.74,
    temp_std   = 2.7,
    temp_dof   = 6.0,
    rain_mean  = 2.16,   # mm/day ≈ 790 mm/yr
    rain_amp   = 1.9,
    rain_peak  = 355,    # wettest day ≈ December 21
    rain_ar1   = 0.46,
    rain_std   = 3.6,
    rain_dof   = 4.0,
    seed       = 2024,
)
REF_OUT_PATH = Path("data/sicily_reference_synthetic.csv")


# ===========================================================================
# Real ERA5 downloader
# ===========================================================================

def download_era5(
        raw_path: Path = ERA5_RAW_PATH,
        out_path: Path = ERA5_OUT_PATH,
) -> pd.DataFrame:
    """
    Download ERA5 reanalysis data for Sicily and export to pipeline CSV.

    Requires cdsapi + xarray + netCDF4 and a configured ~/.cdsapirc.
    Raw NetCDF is cached at raw_path (~150 MB) to avoid re-downloading.

    Returns
    -------
    pd.DataFrame with columns [date, temperature_c, rainfall_mm].
    """
    try:
        import cdsapi
        import xarray as xr
    except ImportError:
        raise ImportError(
            "Missing dependencies. Run: pip install cdsapi xarray netCDF4"
        )

    raw_path.parent.mkdir(parents=True, exist_ok=True)

    if not raw_path.exists():
        log.info("Downloading ERA5 data for Sicily 1990–2023 (~150 MB) ...")
        c = cdsapi.Client()
        c.retrieve(
            ERA5_DATASET,
            {
                "product_type": "reanalysis",
                "variable":     ERA5_VARS,
                "year":         [str(y) for y in ERA5_YEARS],
                "month":        ERA5_MONTHS,
                "day":          ERA5_DAYS,
                "time":         ERA5_TIME,
                "area":         ERA5_AREA,
                "format":       "netcdf",
            },
            str(raw_path),
        )
        log.info("Download complete → %s", raw_path)
    else:
        log.info("ERA5 raw file cached at %s — skipping download.", raw_path)

    log.info("Processing ERA5 NetCDF → daily CSV ...")
    import xarray as xr
    ds = xr.open_dataset(raw_path)

    # Spatial mean over the Sicily domain
    t2m = ds["t2m"].mean(dim=["latitude", "longitude"])   # K
    tp  = ds["tp"].mean(dim=["latitude", "longitude"])    # m

    temperature = (t2m.values - 273.15).round(3)           # K → °C
    rainfall    = np.maximum(tp.values * 1000.0, 0.0).round(3)  # m → mm/day

    dates = pd.DatetimeIndex(ds["time"].values).normalize()
    ds.close()

    df = pd.DataFrame({
        "date":          dates,
        "temperature_c": temperature,
        "rainfall_mm":   rainfall,
    })
    df = (df.drop_duplicates("date")
            .sort_values("date")
            .reset_index(drop=True))
    df = df[(df["date"] >= "1990-01-01") & (df["date"] <= "2023-12-31")]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)

    log.info(
        "✓  ERA5 CSV written: %d observations (%s → %s) → %s",
        len(df), df["date"].iloc[0].date(), df["date"].iloc[-1].date(), out_path,
    )
    log.info(
        "   T_mean=%.2f°C  Rain_mean=%.3f mm/day (%.0f mm/yr)",
        df["temperature_c"].mean(),
        df["rainfall_mm"].mean(),
        df["rainfall_mm"].mean() * 365.25,
    )
    return df


# ===========================================================================
# Reference synthetic dataset generator
# ===========================================================================

def _validate_dataset(df: pd.DataFrame, label: str) -> None:
    """Assert critical statistical properties hold after generation."""
    df2 = df.copy()
    df2["month"] = pd.DatetimeIndex(df2["date"]).month
    monthly = df2.groupby("month")["temperature_c"].mean()

    assert monthly.idxmax() in [7, 8], (
        f"[{label}] Seasonal error: hottest month = {monthly.idxmax()}, "
        "expected July (7) or August (8)."
    )
    assert monthly.idxmin() in [1, 2], (
        f"[{label}] Seasonal error: coldest month = {monthly.idxmin()}, "
        "expected January (1) or February (2)."
    )
    assert (df["rainfall_mm"] >= 0).all(), f"[{label}] Negative rainfall found."
    assert df["temperature_c"].between(-10, 50).all(), \
        f"[{label}] Temperature outside physical range."
    log.info("[%s] Dataset validation passed ✓", label)


def create_reference_dataset(
        out_path: Path = REF_OUT_PATH,
        overwrite: bool = False,
) -> pd.DataFrame:
    """
    Generate and persist the MQFS reference synthetic dataset (1990–2023).

    ⚠  This is NOT real data. It is a calibrated simulation that ships
       with the repository so the pipeline works without any API key.

    Statistical properties of the output
    -------------------------------------
    Rows            : 12,418 daily observations
    Date range      : 1990-01-01 → 2023-12-31
    Temp mean       : ~18.4°C  (hottest month July, coldest January)
    Rain mean       : ~2.16 mm/day  (~790 mm/yr, wettest month December)
    Drought R*      : 1.8231 mm/day (growing-season May–Aug mean)
    Historical K    : 1.0162 mm/day (65th-pct annual CDI → P(trigger)≈35%)
    """
    if out_path.exists() and not overwrite:
        log.info("Reference dataset exists at %s — skipping generation.", out_path)
        return pd.read_csv(out_path, parse_dates=["date"])

    p   = REF_PARAMS
    rng = np.random.default_rng(p["seed"])

    dates = pd.date_range(p["start"], p["end"], freq="D")
    n     = len(dates)
    doy   = dates.day_of_year.to_numpy(float)

    # Temperature
    phase_t   = 2.0 * np.pi * (doy - p["temp_peak"]) / 365.25
    temp_seas = p["temp_mean"] + p["temp_amp"] * np.cos(phase_t)
    innov_t   = student_t.rvs(df=p["temp_dof"], size=n,
                               random_state=int(rng.integers(1_000_000_000)))
    innov_t  *= p["temp_std"] / np.std(innov_t)
    resid_t   = np.zeros(n)
    for i in range(1, n):
        resid_t[i] = p["temp_ar1"] * resid_t[i - 1] + innov_t[i]
    temperature = (temp_seas + resid_t).round(3)

    # Rainfall
    phase_r   = 2.0 * np.pi * (doy - p["rain_peak"]) / 365.25
    rain_seas = np.maximum(p["rain_mean"] + p["rain_amp"] * np.cos(phase_r), 0.05)
    innov_r   = student_t.rvs(df=p["rain_dof"], size=n,
                               random_state=int(rng.integers(1_000_000_000)))
    innov_r  *= p["rain_std"] / np.std(innov_r)
    resid_r   = np.zeros(n)
    for i in range(1, n):
        resid_r[i] = p["rain_ar1"] * resid_r[i - 1] + innov_r[i]
    rainfall = np.maximum(rain_seas + resid_r, 0.0).round(3)

    df = pd.DataFrame({
        "date":          dates,
        "temperature_c": temperature,
        "rainfall_mm":   rainfall,
    })

    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)

    _validate_dataset(df, "reference_synthetic")
    log.info(
        "⚠  Reference synthetic dataset written → %s (%d rows). NOT real data.",
        out_path, len(df),
    )
    return df


# ===========================================================================
# CLI
# ===========================================================================

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="MQFS — ERA5 downloader and reference dataset generator"
    )
    parser.add_argument(
        "--real", action="store_true",
        help="Download real ERA5 data (requires ~/.cdsapirc).",
    )
    parser.add_argument(
        "--overwrite", action="store_true",
        help="Overwrite existing output files.",
    )
    args = parser.parse_args()

    if args.real:
        log.info("=== Downloading real ERA5 data for Sicily ===")
        download_era5()
    else:
        log.info("=== Generating MQFS reference synthetic dataset ===")
        create_reference_dataset(overwrite=args.overwrite)
        log.info(
            "To use real ERA5 data: python src/python/era5_fetcher.py --real"
        )
